### ISSUE TITLE
NPM Publishing step does not include scripts/install-pulumi-plugin.js

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-package-publisher#10]
### What happened?

See: 
- pulumi/pulumi-azure#1301

NPM install fails for packages published with the latest version of pulumi-package-publisher.

This is likely due to the publisher action not performing these steps from the ci-scripts repository, which inject an install-pulumi-plugin.js into the package:

https://github.com/pulumi/scripts/blob/b6ee1692954d2b39e7a22b0db80b8cc4b735c101/ci/publish-tfgen-package#L29-L40

### Expected Behavior

NPM install succeeds, installs plugin.

### Steps to reproduce

Run `npm install @pulumi/azure@v5.44.0`

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I don't think this is a problem with the cli's publish command per-se. If I run gen-sdk I can see the install-pulumi-plugin.js script is emitted correctly to scripts/ and is referenced by the package.json. 
The publish command just runs publish against a folder containing a package.json and if I point it directly to one from codegen it does include the plugin script.

The issue comes from that actually doing a proper publish still requires provider workflows to take the codegen folder, copy it, edit the package.json to fill in the version, and then tell the CLI to publish that. You need to fix up provider workflows so that the above referenced copy keeps the scripts directory. I think the bit that needs fixing is the makefiles (e.g. https://github.com/pulumi/pulumi-github/blob/master/Makefile#L59) where you ran yarn install and then copy across some of the files.

Really this is a hell of a messy way to do npm publishing and very non-standard as far as I can make out, but it's a bit of a mess to untangle it all at once.

**Comment by AaronFriel** [comment]
@Frassle Yeah, agreed - I'd like to simplify this makefile target down to `gen-sdk`, and the publishing target down to `publish-sdk`.

**Comment by Frassle** [comment]
> I'd like to simplify this makefile target down to gen-sdk, and the publishing target down to publish-sdk.

Likewise but we'll have to work out where to slot the version information in as part of that.
It feels like either gen-sdk needs to generate the version information (I was looking at doing this in https://github.com/pulumi/pulumi/pull/12576), or publish-sdk needs to take a version argument and fill in the sdk version as part of packing and publishing.

Given that we also want to be able to split this workflow into three (gen, pack, publish) so that we can test the artifacts to be released (talk to @danielrbradley for why) the version info needs to at least be insertable at the pack point not just the publish point. If it is a parameter to pack/publish then there's user responsibility of making sure it matches the schema (because it should), which feels like a small nudge that it should be part of gen-sdk to me. That however clashes badly with the fact that we check-in the gen'd sdks and check there's no worktree diffs if regenerated in CI.

So yeh not sure how we solve this one, but something we all ought to think about.

**Comment by AaronFriel** [comment]
I believe publishing needs to include it. Our process is to not include version information in SDKs right now and this allows us to make a release without code changes (tagging the unversioned SDKs).

It would be a major change to our process we'd need to understand to put versioning in the SDK gen side.
